config/routes.rb
Rails.application.routes.draw do
  get 'input_urls/index'

  root 'input_urls#index'


  resources :input_urls, except: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_model.rb
class CarModel < ApplicationRecord

  belongs_to :input_url
  has_many :model_versions, dependent: :destroy
end

app/models/input_url.rb
class InputUrl < ApplicationRecord

  has_many :car_models, dependent: :destroy

  validates_presence_of :url
  validates :url, format: URI::regexp(%w[http https])
  
end

app/models/model_version.rb
class ModelVersion < ApplicationRecord

  belongs_to :car_model
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :danger, :info
end

app/controllers/concerns/input_urls/scraper_api.rb
module InputUrls::ScraperApi
  extend ActiveSupport::Concern

  require 'open-uri'

  def get_page target_url
    @doc   = Nokogiri::HTML(open(target_url.url))
    models = get_car_models(target_url)
    get_model_versions target_url
  end 

  def get_car_models target_url
    models = []
    @doc.css('.list-models').each do |type|
      if type.css('a.lazy_models').length > 0
        model = type.css('h3').first.text.strip
        url   =  type.css('a.lazy_models').first.attribute('href').value 
        target_url.car_models.create(name: model, url: "https://uae.yallamotor.com#{url}")
      end
    end
    models
  end

  def get_model_versions target_url
    target_url.car_models.each do |car_model|
      Nokogiri::HTML(open(car_model.url)).css('div.match-version').each do |version|
        if version.css('h3.pro-name').length > 0
          version_name = version.css('h3.pro-name').first.text.strip
        end
        if version.css('span.pro-pice').length > 0
          version_price = version.css('span.pro-pice').first.text.strip
        end
        car_model.model_versions.create(version_name: version_name, version_price: version_price)
      end
    end
  end
end

app/controllers/input_urls_controller.rb
class InputUrlsController < ApplicationController

  include InputUrls::ScraperApi

  before_action :set_input_url, only: [:show, :destroy]

  def index
    @input_url  = InputUrl.new
    set_all_urls
  end

  def create
    input_url = InputUrl.new(url_params)
    if input_url.save
      get_page(input_url)
      flash!(notice: t('controllers.input_urls.create.flash.notice'))
    else
      flash!(alert: t('.alert', msg: input_url.errors.full_messages.to_sentence))
    end
    set_all_urls
    redirect_to root_path
  end

  def show
    @car_models = @input_url.car_models.includes(:model_versions)
  end

  def destroy
    @input_url.destroy
    set_all_urls
    redirect_to root_path
  end

  private

    def set_input_url
      @input_url = InputUrl.find_by_id(params[:id])
    end

    def url_params
      params.require(:input_url).permit(:url)
    end

    def set_all_urls
      @input_urls = InputUrl.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/input_urls_helper.rb
module InputUrlsHelper
end

app/views/input_urls/index.html.haml
= stylesheet_link_tag 'input_urls'
= javascript_include_tag "input_urls"

%section
  #carouselExampleFade.carousel.slide.carousel-fade{"data-ride" => "carousel"}
    .carousel-inner
      .carousel-item.active
        %img.d-block.w-100{:alt => "...", :src => "https://ymimg1.b8cdn.com/resized/spotlight/856/web_artwork/webp_spotlight_web_New_Cars_Make_Desktop_Spotlight_Image.webp"}
%section.header
  .row.pt-1.pb-1
    .col-lg-12
      %h3.text-center YallaMotor Scraper
      %h5.text-center - scrapes pages and sub-pages -
%section.search-sec
  .container#input-urls-wrapper
    = render 'input_urls/partials/form', input_url: @input_url
%section.section-table
  = render 'input_urls/partials/urls', input_urls: @input_urls
%section.section-footer    
  .container
    .row
      .col-lg-12
        .row
          .col-lg-9.col-md-9.col-sm-12.p-0
            %b
              Assessment Task for the post Software Engineer.
          .col-lg-3.col-md-3.col-sm-12.p-0
            %b
              Developed By:
              Ahsan Awan
              devahsan.awan@gmail.com

app/views/input_urls/partials/_form.html.haml
= simple_form_for input_url ,url: input_urls_path, method: :post do |f|    
  .row
    .col-lg-12
      .row
        .col-lg-9.col-md-9.col-sm-12.p-0
          = f.input :url, required: true, label: false, class: 'form-control search-slt target_url_input' , step: :any, as: :url, placeholder: "http://uae.yallamotor.com/new-cars/toyota"
        .col-lg-3.col-md-3.col-sm-12.p-0
          = f.submit "Scrape", data: {disable_with: "Scraping..."}, class: "btn btn-danger wrn-btn", id:"submit", onclick: "return validateform();"
        %p.error_messages

app/views/input_urls/partials/_show.html.haml
.container
  .row.pt-1.pb-1
    .col-lg-1
      %h1.text-left.inline.home-link
        = link_to root_path do
          %i.fa.fa-home
    .col-lg-11
      %h3.text-center 
        = "Results for #{@input_url.url.split('/').last.try(:titleize)}"
      %h5.text-center 
        = "Scraped at (#{@input_url.created_at.strftime('%b %d, %Y')})"
  .row
    %table#results-table.stripe.row-border.order-column.table-striped.table-bordered{:cellspacing => "0", :width => "100%"}
      %thead
        %tr
          %th Type
          %th Title
          %th Price
      %tbody
        - car_models.each do |car_model|
          %tr
            %td 
              %b
                = "Car Model"
            %td
              %b
                = car_model.name
            %td
          - car_model.model_versions.each do |model_version|
            %tr
              %td 
                = "Car Version"
              %td
                = model_version.version_name
              %td
                = model_version.version_price

app/views/input_urls/partials/_urls.html.haml
.container
  %h3.text-center Previously Scraped Data
  .row
    %table#urls-table.stripe.row-border.order-column{:cellspacing => "0", :width => "100%"}
      %thead
        %tr
          %th No.
          %th Company
          %th URL
          %th Scraped At
          %th Actions
      %tbody
        - input_urls.each_with_index do |input_url, index|
          %tr
            %td 
              = "#{index+1}."
            %td
              = input_url.url.split('/').last.try(:titleize)
            %td
              = input_url.url
            %td
              = input_url.created_at.strftime('%b %d, %Y')
            %td
              = link_to input_url_path(input_url), remote: true do
                %span.tooltip_span{"data-placement" => "top", "data-toggle" => "tooltip", :title => "View Results"}
                  %i.fa.fa-eye
              = link_to input_url_path(input_url), method: 'delete' do
                %span.tooltip_span{"data-placement" => "top", "data-toggle" => "tooltip", :title => "Delete"}
                  .fa.fa-times.text-danger

app/views/input_urls/show.js.haml
$('.section-table').html("#{(escape_javascript( render :partial => 'input_urls/partials/show', locals: {car_models: @car_models }))}");
$('#resuts-table').dataTable()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YallaMotors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>